/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as CareerAdvisorRouteImport } from './routes/career-advisor'
import { Route as CareerInsightsRouteImport } from './routes/career-insights'
import { Route as CollegeAccessRouteImport } from './routes/college-access'
import { Route as EmployerAccessRouteImport } from './routes/employer-access'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as UpskillingRouteImport } from './routes/upskilling'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCollegesRouteImport } from './routes/admin.colleges'
import { Route as AdminEmployersRouteImport } from './routes/admin.employers'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminVerificationRouteImport } from './routes/admin.verification'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppApplicationsRouteImport } from './routes/app.applications'
import { Route as AppCareerAdvisorRouteImport } from './routes/app.career-advisor'
import { Route as AppCareerInsightsRouteImport } from './routes/app.career-insights'
import { Route as AppJobsRouteImport } from './routes/app.jobs'
import { Route as AppMockInterviewRouteImport } from './routes/app.mock-interview'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSkillGapRouteImport } from './routes/app.skill-gap'
import { Route as AppSkillPassportRouteImport } from './routes/app.skill-passport'
import { Route as AppUpskillingRouteImport } from './routes/app.upskilling'
import { Route as AppCollegeIndexRouteImport } from './routes/app.college.index'
import { Route as AppCollegeAssessmentsRouteImport } from './routes/app.college.assessments'
import { Route as AppCollegeCompaniesRouteImport } from './routes/app.college.companies'
import { Route as AppCollegeDrivesRouteImport } from './routes/app.college.drives'
import { Route as AppCollegeHackathonsRouteImport } from './routes/app.college.hackathons'
import { Route as AppCollegePlacementsRouteImport } from './routes/app.college.placements'
import { Route as AppCollegeReportsRouteImport } from './routes/app.college.reports'
import { Route as AppCollegeSkillsRouteImport } from './routes/app.college.skills'
import { Route as AppCollegeStudentsRouteImport } from './routes/app.college.students'
import { Route as AppEmployerIndexRouteImport } from './routes/app.employer.index'
import { Route as AppEmployerAnalyticsRouteImport } from './routes/app.employer.analytics'
import { Route as AppEmployerAssessmentsRouteImport } from './routes/app.employer.assessments'
import { Route as AppEmployerAtsRouteImport } from './routes/app.employer.ats'
import { Route as AppEmployerCandidatesRouteImport } from './routes/app.employer.candidates'
import { Route as AppEmployerInsightsRouteImport } from './routes/app.employer.insights'
import { Route as AppEmployerInterviewsRouteImport } from './routes/app.employer.interviews'
import { Route as AppEmployerJobsRouteImport } from './routes/app.employer.jobs'
import { Route as AppEmployerOffersRouteImport } from './routes/app.employer.offers'
import { Route as AppEmployerStaffingRouteImport } from './routes/app.employer.staffing'
import { Route as AppEmployerTalentSearchRouteImport } from './routes/app.employer.talent-search'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerAdvisorRoute = CareerAdvisorRouteImport.update({
  id: '/career-advisor',
  path: '/career-advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerInsightsRoute = CareerInsightsRouteImport.update({
  id: '/career-insights',
  path: '/career-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeAccessRoute = CollegeAccessRouteImport.update({
  id: '/college-access',
  path: '/college-access',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerAccessRoute = EmployerAccessRouteImport.update({
  id: '/employer-access',
  path: '/employer-access',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const UpskillingRoute = UpskillingRouteImport.update({
  id: '/upskilling',
  path: '/upskilling',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollegesRoute = AdminCollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployersRoute = AdminEmployersRouteImport.update({
  id: '/employers',
  path: '/employers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppCareerAdvisorRoute = AppCareerAdvisorRouteImport.update({
  id: '/career-advisor',
  path: '/career-advisor',
  getParentRoute: () => AppRoute,
} as any)
const AppCareerInsightsRoute = AppCareerInsightsRouteImport.update({
  id: '/career-insights',
  path: '/career-insights',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppMockInterviewRoute = AppMockInterviewRouteImport.update({
  id: '/mock-interview',
  path: '/mock-interview',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillGapRoute = AppSkillGapRouteImport.update({
  id: '/skill-gap',
  path: '/skill-gap',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillPassportRoute = AppSkillPassportRouteImport.update({
  id: '/skill-passport',
  path: '/skill-passport',
  getParentRoute: () => AppRoute,
} as any)
const AppUpskillingRoute = AppUpskillingRouteImport.update({
  id: '/upskilling',
  path: '/upskilling',
  getParentRoute: () => AppRoute,
} as any)
const AppCollegeIndexRoute = AppCollegeIndexRouteImport.update({
  id: '/college/',
  path: '/college/',
  getParentRoute: () => AppRoute,
} as any)
const AppCollegeAssessmentsRoute = AppCollegeAssessmentsRouteImport.update({
  id: '/college/assessments',
  path: '/college/assessments',
  getParentRoute: () => AppRoute,
} as any)
const AppCollegeCompaniesRoute = AppCollegeCompaniesRouteImport.update({
  id: '/college/companies',
  path: '/college/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppCollegeDrivesRoute = AppCollegeDrivesRouteImport.update({
  id: '/college/drives',
  path: '/college/drives',
  getParentRoute: () => AppRoute,
} as any)
const AppCollegeHackathonsRoute = AppCollegeHackathonsRouteImport.update({
  id: '/college/hackathons',
  path: '/college/hackathons',
  getParentRoute: () => AppRoute,
} as any)
const AppCollegePlacementsRoute = AppCollegePlacementsRouteImport.update({
  id: '/college/placements',
  path: '/college/placements',
  getParentRoute: () => AppRoute,
} as any)
const AppCollegeReportsRoute = AppCollegeReportsRouteImport.update({
  id: '/college/reports',
  path: '/college/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppCollegeSkillsRoute = AppCollegeSkillsRouteImport.update({
  id: '/college/skills',
  path: '/college/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppCollegeStudentsRoute = AppCollegeStudentsRouteImport.update({
  id: '/college/students',
  path: '/college/students',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployerIndexRoute = AppEmployerIndexRouteImport.update({
  id: '/employer/',
  path: '/employer/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployerAnalyticsRoute = AppEmployerAnalyticsRouteImport.update({
  id: '/employer/analytics',
  path: '/employer/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployerAssessmentsRoute = AppEmployerAssessmentsRouteImport.update({
  id: '/employer/assessments',
  path: '/employer/assessments',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployerAtsRoute = AppEmployerAtsRouteImport.update({
  id: '/employer/ats',
  path: '/employer/ats',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployerCandidatesRoute = AppEmployerCandidatesRouteImport.update({
  id: '/employer/candidates',
  path: '/employer/candidates',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployerInsightsRoute = AppEmployerInsightsRouteImport.update({
  id: '/employer/insights',
  path: '/employer/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployerInterviewsRoute = AppEmployerInterviewsRouteImport.update({
  id: '/employer/interviews',
  path: '/employer/interviews',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployerJobsRoute = AppEmployerJobsRouteImport.update({
  id: '/employer/jobs',
  path: '/employer/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployerOffersRoute = AppEmployerOffersRouteImport.update({
  id: '/employer/offers',
  path: '/employer/offers',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployerStaffingRoute = AppEmployerStaffingRouteImport.update({
  id: '/employer/staffing',
  path: '/employer/staffing',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployerTalentSearchRoute = AppEmployerTalentSearchRouteImport.update({
  id: '/employer/talent-search',
  path: '/employer/talent-search',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/career-advisor': typeof CareerAdvisorRoute
  '/career-insights': typeof CareerInsightsRoute
  '/college-access': typeof CollegeAccessRoute
  '/employer-access': typeof EmployerAccessRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/upskilling': typeof UpskillingRoute
  '/admin/colleges': typeof AdminCollegesRoute
  '/admin/employers': typeof AdminEmployersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/career-advisor': typeof AppCareerAdvisorRoute
  '/app/career-insights': typeof AppCareerInsightsRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/mock-interview': typeof AppMockInterviewRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/skill-gap': typeof AppSkillGapRoute
  '/app/skill-passport': typeof AppSkillPassportRoute
  '/app/upskilling': typeof AppUpskillingRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/college/assessments': typeof AppCollegeAssessmentsRoute
  '/app/college/companies': typeof AppCollegeCompaniesRoute
  '/app/college/drives': typeof AppCollegeDrivesRoute
  '/app/college/hackathons': typeof AppCollegeHackathonsRoute
  '/app/college/placements': typeof AppCollegePlacementsRoute
  '/app/college/reports': typeof AppCollegeReportsRoute
  '/app/college/skills': typeof AppCollegeSkillsRoute
  '/app/college/students': typeof AppCollegeStudentsRoute
  '/app/employer/analytics': typeof AppEmployerAnalyticsRoute
  '/app/employer/assessments': typeof AppEmployerAssessmentsRoute
  '/app/employer/ats': typeof AppEmployerAtsRoute
  '/app/employer/candidates': typeof AppEmployerCandidatesRoute
  '/app/employer/insights': typeof AppEmployerInsightsRoute
  '/app/employer/interviews': typeof AppEmployerInterviewsRoute
  '/app/employer/jobs': typeof AppEmployerJobsRoute
  '/app/employer/offers': typeof AppEmployerOffersRoute
  '/app/employer/staffing': typeof AppEmployerStaffingRoute
  '/app/employer/talent-search': typeof AppEmployerTalentSearchRoute
  '/app/college/': typeof AppCollegeIndexRoute
  '/app/employer/': typeof AppEmployerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/career-advisor': typeof CareerAdvisorRoute
  '/career-insights': typeof CareerInsightsRoute
  '/college-access': typeof CollegeAccessRoute
  '/employer-access': typeof EmployerAccessRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/upskilling': typeof UpskillingRoute
  '/admin/colleges': typeof AdminCollegesRoute
  '/admin/employers': typeof AdminEmployersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/career-advisor': typeof AppCareerAdvisorRoute
  '/app/career-insights': typeof AppCareerInsightsRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/mock-interview': typeof AppMockInterviewRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/skill-gap': typeof AppSkillGapRoute
  '/app/skill-passport': typeof AppSkillPassportRoute
  '/app/upskilling': typeof AppUpskillingRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/app/college/assessments': typeof AppCollegeAssessmentsRoute
  '/app/college/companies': typeof AppCollegeCompaniesRoute
  '/app/college/drives': typeof AppCollegeDrivesRoute
  '/app/college/hackathons': typeof AppCollegeHackathonsRoute
  '/app/college/placements': typeof AppCollegePlacementsRoute
  '/app/college/reports': typeof AppCollegeReportsRoute
  '/app/college/skills': typeof AppCollegeSkillsRoute
  '/app/college/students': typeof AppCollegeStudentsRoute
  '/app/employer/analytics': typeof AppEmployerAnalyticsRoute
  '/app/employer/assessments': typeof AppEmployerAssessmentsRoute
  '/app/employer/ats': typeof AppEmployerAtsRoute
  '/app/employer/candidates': typeof AppEmployerCandidatesRoute
  '/app/employer/insights': typeof AppEmployerInsightsRoute
  '/app/employer/interviews': typeof AppEmployerInterviewsRoute
  '/app/employer/jobs': typeof AppEmployerJobsRoute
  '/app/employer/offers': typeof AppEmployerOffersRoute
  '/app/employer/staffing': typeof AppEmployerStaffingRoute
  '/app/employer/talent-search': typeof AppEmployerTalentSearchRoute
  '/app/college': typeof AppCollegeIndexRoute
  '/app/employer': typeof AppEmployerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/career-advisor': typeof CareerAdvisorRoute
  '/career-insights': typeof CareerInsightsRoute
  '/college-access': typeof CollegeAccessRoute
  '/employer-access': typeof EmployerAccessRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/upskilling': typeof UpskillingRoute
  '/admin/colleges': typeof AdminCollegesRoute
  '/admin/employers': typeof AdminEmployersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/career-advisor': typeof AppCareerAdvisorRoute
  '/app/career-insights': typeof AppCareerInsightsRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/mock-interview': typeof AppMockInterviewRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/skill-gap': typeof AppSkillGapRoute
  '/app/skill-passport': typeof AppSkillPassportRoute
  '/app/upskilling': typeof AppUpskillingRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/college/assessments': typeof AppCollegeAssessmentsRoute
  '/app/college/companies': typeof AppCollegeCompaniesRoute
  '/app/college/drives': typeof AppCollegeDrivesRoute
  '/app/college/hackathons': typeof AppCollegeHackathonsRoute
  '/app/college/placements': typeof AppCollegePlacementsRoute
  '/app/college/reports': typeof AppCollegeReportsRoute
  '/app/college/skills': typeof AppCollegeSkillsRoute
  '/app/college/students': typeof AppCollegeStudentsRoute
  '/app/employer/analytics': typeof AppEmployerAnalyticsRoute
  '/app/employer/assessments': typeof AppEmployerAssessmentsRoute
  '/app/employer/ats': typeof AppEmployerAtsRoute
  '/app/employer/candidates': typeof AppEmployerCandidatesRoute
  '/app/employer/insights': typeof AppEmployerInsightsRoute
  '/app/employer/interviews': typeof AppEmployerInterviewsRoute
  '/app/employer/jobs': typeof AppEmployerJobsRoute
  '/app/employer/offers': typeof AppEmployerOffersRoute
  '/app/employer/staffing': typeof AppEmployerStaffingRoute
  '/app/employer/talent-search': typeof AppEmployerTalentSearchRoute
  '/app/college/': typeof AppCollegeIndexRoute
  '/app/employer/': typeof AppEmployerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/career-advisor'
    | '/career-insights'
    | '/college-access'
    | '/employer-access'
    | '/jobs'
    | '/login'
    | '/signup'
    | '/upskilling'
    | '/admin/colleges'
    | '/admin/employers'
    | '/admin/users'
    | '/admin/verification'
    | '/app/applications'
    | '/app/career-advisor'
    | '/app/career-insights'
    | '/app/jobs'
    | '/app/mock-interview'
    | '/app/profile'
    | '/app/settings'
    | '/app/skill-gap'
    | '/app/skill-passport'
    | '/app/upskilling'
    | '/admin/'
    | '/app/'
    | '/app/college/assessments'
    | '/app/college/companies'
    | '/app/college/drives'
    | '/app/college/hackathons'
    | '/app/college/placements'
    | '/app/college/reports'
    | '/app/college/skills'
    | '/app/college/students'
    | '/app/employer/analytics'
    | '/app/employer/assessments'
    | '/app/employer/ats'
    | '/app/employer/candidates'
    | '/app/employer/insights'
    | '/app/employer/interviews'
    | '/app/employer/jobs'
    | '/app/employer/offers'
    | '/app/employer/staffing'
    | '/app/employer/talent-search'
    | '/app/college/'
    | '/app/employer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/career-advisor'
    | '/career-insights'
    | '/college-access'
    | '/employer-access'
    | '/jobs'
    | '/login'
    | '/signup'
    | '/upskilling'
    | '/admin/colleges'
    | '/admin/employers'
    | '/admin/users'
    | '/admin/verification'
    | '/app/applications'
    | '/app/career-advisor'
    | '/app/career-insights'
    | '/app/jobs'
    | '/app/mock-interview'
    | '/app/profile'
    | '/app/settings'
    | '/app/skill-gap'
    | '/app/skill-passport'
    | '/app/upskilling'
    | '/admin'
    | '/app'
    | '/app/college/assessments'
    | '/app/college/companies'
    | '/app/college/drives'
    | '/app/college/hackathons'
    | '/app/college/placements'
    | '/app/college/reports'
    | '/app/college/skills'
    | '/app/college/students'
    | '/app/employer/analytics'
    | '/app/employer/assessments'
    | '/app/employer/ats'
    | '/app/employer/candidates'
    | '/app/employer/insights'
    | '/app/employer/interviews'
    | '/app/employer/jobs'
    | '/app/employer/offers'
    | '/app/employer/staffing'
    | '/app/employer/talent-search'
    | '/app/college'
    | '/app/employer'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/career-advisor'
    | '/career-insights'
    | '/college-access'
    | '/employer-access'
    | '/jobs'
    | '/login'
    | '/signup'
    | '/upskilling'
    | '/admin/colleges'
    | '/admin/employers'
    | '/admin/users'
    | '/admin/verification'
    | '/app/applications'
    | '/app/career-advisor'
    | '/app/career-insights'
    | '/app/jobs'
    | '/app/mock-interview'
    | '/app/profile'
    | '/app/settings'
    | '/app/skill-gap'
    | '/app/skill-passport'
    | '/app/upskilling'
    | '/admin/'
    | '/app/'
    | '/app/college/assessments'
    | '/app/college/companies'
    | '/app/college/drives'
    | '/app/college/hackathons'
    | '/app/college/placements'
    | '/app/college/reports'
    | '/app/college/skills'
    | '/app/college/students'
    | '/app/employer/analytics'
    | '/app/employer/assessments'
    | '/app/employer/ats'
    | '/app/employer/candidates'
    | '/app/employer/insights'
    | '/app/employer/interviews'
    | '/app/employer/jobs'
    | '/app/employer/offers'
    | '/app/employer/staffing'
    | '/app/employer/talent-search'
    | '/app/college/'
    | '/app/employer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  CareerAdvisorRoute: typeof CareerAdvisorRoute
  CareerInsightsRoute: typeof CareerInsightsRoute
  CollegeAccessRoute: typeof CollegeAccessRoute
  EmployerAccessRoute: typeof EmployerAccessRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  UpskillingRoute: typeof UpskillingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-advisor': {
      id: '/career-advisor'
      path: '/career-advisor'
      fullPath: '/career-advisor'
      preLoaderRoute: typeof CareerAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-insights': {
      id: '/career-insights'
      path: '/career-insights'
      fullPath: '/career-insights'
      preLoaderRoute: typeof CareerInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college-access': {
      id: '/college-access'
      path: '/college-access'
      fullPath: '/college-access'
      preLoaderRoute: typeof CollegeAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer-access': {
      id: '/employer-access'
      path: '/employer-access'
      fullPath: '/employer-access'
      preLoaderRoute: typeof EmployerAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upskilling': {
      id: '/upskilling'
      path: '/upskilling'
      fullPath: '/upskilling'
      preLoaderRoute: typeof UpskillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/colleges': {
      id: '/admin/colleges'
      path: '/colleges'
      fullPath: '/admin/colleges'
      preLoaderRoute: typeof AdminCollegesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employers': {
      id: '/admin/employers'
      path: '/employers'
      fullPath: '/admin/employers'
      preLoaderRoute: typeof AdminEmployersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/applications': {
      id: '/app/applications'
      path: '/applications'
      fullPath: '/app/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/career-advisor': {
      id: '/app/career-advisor'
      path: '/career-advisor'
      fullPath: '/app/career-advisor'
      preLoaderRoute: typeof AppCareerAdvisorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/career-insights': {
      id: '/app/career-insights'
      path: '/career-insights'
      fullPath: '/app/career-insights'
      preLoaderRoute: typeof AppCareerInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jobs': {
      id: '/app/jobs'
      path: '/jobs'
      fullPath: '/app/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mock-interview': {
      id: '/app/mock-interview'
      path: '/mock-interview'
      fullPath: '/app/mock-interview'
      preLoaderRoute: typeof AppMockInterviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/skill-gap': {
      id: '/app/skill-gap'
      path: '/skill-gap'
      fullPath: '/app/skill-gap'
      preLoaderRoute: typeof AppSkillGapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/skill-passport': {
      id: '/app/skill-passport'
      path: '/skill-passport'
      fullPath: '/app/skill-passport'
      preLoaderRoute: typeof AppSkillPassportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/upskilling': {
      id: '/app/upskilling'
      path: '/upskilling'
      fullPath: '/app/upskilling'
      preLoaderRoute: typeof AppUpskillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/college/': {
      id: '/app/college/'
      path: '/college'
      fullPath: '/app/college/'
      preLoaderRoute: typeof AppCollegeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/college/assessments': {
      id: '/app/college/assessments'
      path: '/college/assessments'
      fullPath: '/app/college/assessments'
      preLoaderRoute: typeof AppCollegeAssessmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/college/companies': {
      id: '/app/college/companies'
      path: '/college/companies'
      fullPath: '/app/college/companies'
      preLoaderRoute: typeof AppCollegeCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/college/drives': {
      id: '/app/college/drives'
      path: '/college/drives'
      fullPath: '/app/college/drives'
      preLoaderRoute: typeof AppCollegeDrivesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/college/hackathons': {
      id: '/app/college/hackathons'
      path: '/college/hackathons'
      fullPath: '/app/college/hackathons'
      preLoaderRoute: typeof AppCollegeHackathonsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/college/placements': {
      id: '/app/college/placements'
      path: '/college/placements'
      fullPath: '/app/college/placements'
      preLoaderRoute: typeof AppCollegePlacementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/college/reports': {
      id: '/app/college/reports'
      path: '/college/reports'
      fullPath: '/app/college/reports'
      preLoaderRoute: typeof AppCollegeReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/college/skills': {
      id: '/app/college/skills'
      path: '/college/skills'
      fullPath: '/app/college/skills'
      preLoaderRoute: typeof AppCollegeSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/college/students': {
      id: '/app/college/students'
      path: '/college/students'
      fullPath: '/app/college/students'
      preLoaderRoute: typeof AppCollegeStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employer/': {
      id: '/app/employer/'
      path: '/employer'
      fullPath: '/app/employer/'
      preLoaderRoute: typeof AppEmployerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employer/analytics': {
      id: '/app/employer/analytics'
      path: '/employer/analytics'
      fullPath: '/app/employer/analytics'
      preLoaderRoute: typeof AppEmployerAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employer/assessments': {
      id: '/app/employer/assessments'
      path: '/employer/assessments'
      fullPath: '/app/employer/assessments'
      preLoaderRoute: typeof AppEmployerAssessmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employer/ats': {
      id: '/app/employer/ats'
      path: '/employer/ats'
      fullPath: '/app/employer/ats'
      preLoaderRoute: typeof AppEmployerAtsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employer/candidates': {
      id: '/app/employer/candidates'
      path: '/employer/candidates'
      fullPath: '/app/employer/candidates'
      preLoaderRoute: typeof AppEmployerCandidatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employer/insights': {
      id: '/app/employer/insights'
      path: '/employer/insights'
      fullPath: '/app/employer/insights'
      preLoaderRoute: typeof AppEmployerInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employer/interviews': {
      id: '/app/employer/interviews'
      path: '/employer/interviews'
      fullPath: '/app/employer/interviews'
      preLoaderRoute: typeof AppEmployerInterviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employer/jobs': {
      id: '/app/employer/jobs'
      path: '/employer/jobs'
      fullPath: '/app/employer/jobs'
      preLoaderRoute: typeof AppEmployerJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employer/offers': {
      id: '/app/employer/offers'
      path: '/employer/offers'
      fullPath: '/app/employer/offers'
      preLoaderRoute: typeof AppEmployerOffersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employer/staffing': {
      id: '/app/employer/staffing'
      path: '/employer/staffing'
      fullPath: '/app/employer/staffing'
      preLoaderRoute: typeof AppEmployerStaffingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employer/talent-search': {
      id: '/app/employer/talent-search'
      path: '/employer/talent-search'
      fullPath: '/app/employer/talent-search'
      preLoaderRoute: typeof AppEmployerTalentSearchRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCollegesRoute: typeof AdminCollegesRoute
  AdminEmployersRoute: typeof AdminEmployersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCollegesRoute: AdminCollegesRoute,
  AdminEmployersRoute: AdminEmployersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppCareerAdvisorRoute: typeof AppCareerAdvisorRoute
  AppCareerInsightsRoute: typeof AppCareerInsightsRoute
  AppJobsRoute: typeof AppJobsRoute
  AppMockInterviewRoute: typeof AppMockInterviewRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSkillGapRoute: typeof AppSkillGapRoute
  AppSkillPassportRoute: typeof AppSkillPassportRoute
  AppUpskillingRoute: typeof AppUpskillingRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCollegeAssessmentsRoute: typeof AppCollegeAssessmentsRoute
  AppCollegeCompaniesRoute: typeof AppCollegeCompaniesRoute
  AppCollegeDrivesRoute: typeof AppCollegeDrivesRoute
  AppCollegeHackathonsRoute: typeof AppCollegeHackathonsRoute
  AppCollegePlacementsRoute: typeof AppCollegePlacementsRoute
  AppCollegeReportsRoute: typeof AppCollegeReportsRoute
  AppCollegeSkillsRoute: typeof AppCollegeSkillsRoute
  AppCollegeStudentsRoute: typeof AppCollegeStudentsRoute
  AppEmployerAnalyticsRoute: typeof AppEmployerAnalyticsRoute
  AppEmployerAssessmentsRoute: typeof AppEmployerAssessmentsRoute
  AppEmployerAtsRoute: typeof AppEmployerAtsRoute
  AppEmployerCandidatesRoute: typeof AppEmployerCandidatesRoute
  AppEmployerInsightsRoute: typeof AppEmployerInsightsRoute
  AppEmployerInterviewsRoute: typeof AppEmployerInterviewsRoute
  AppEmployerJobsRoute: typeof AppEmployerJobsRoute
  AppEmployerOffersRoute: typeof AppEmployerOffersRoute
  AppEmployerStaffingRoute: typeof AppEmployerStaffingRoute
  AppEmployerTalentSearchRoute: typeof AppEmployerTalentSearchRoute
  AppCollegeIndexRoute: typeof AppCollegeIndexRoute
  AppEmployerIndexRoute: typeof AppEmployerIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApplicationsRoute: AppApplicationsRoute,
  AppCareerAdvisorRoute: AppCareerAdvisorRoute,
  AppCareerInsightsRoute: AppCareerInsightsRoute,
  AppJobsRoute: AppJobsRoute,
  AppMockInterviewRoute: AppMockInterviewRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSkillGapRoute: AppSkillGapRoute,
  AppSkillPassportRoute: AppSkillPassportRoute,
  AppUpskillingRoute: AppUpskillingRoute,
  AppIndexRoute: AppIndexRoute,
  AppCollegeAssessmentsRoute: AppCollegeAssessmentsRoute,
  AppCollegeCompaniesRoute: AppCollegeCompaniesRoute,
  AppCollegeDrivesRoute: AppCollegeDrivesRoute,
  AppCollegeHackathonsRoute: AppCollegeHackathonsRoute,
  AppCollegePlacementsRoute: AppCollegePlacementsRoute,
  AppCollegeReportsRoute: AppCollegeReportsRoute,
  AppCollegeSkillsRoute: AppCollegeSkillsRoute,
  AppCollegeStudentsRoute: AppCollegeStudentsRoute,
  AppEmployerAnalyticsRoute: AppEmployerAnalyticsRoute,
  AppEmployerAssessmentsRoute: AppEmployerAssessmentsRoute,
  AppEmployerAtsRoute: AppEmployerAtsRoute,
  AppEmployerCandidatesRoute: AppEmployerCandidatesRoute,
  AppEmployerInsightsRoute: AppEmployerInsightsRoute,
  AppEmployerInterviewsRoute: AppEmployerInterviewsRoute,
  AppEmployerJobsRoute: AppEmployerJobsRoute,
  AppEmployerOffersRoute: AppEmployerOffersRoute,
  AppEmployerStaffingRoute: AppEmployerStaffingRoute,
  AppEmployerTalentSearchRoute: AppEmployerTalentSearchRoute,
  AppCollegeIndexRoute: AppCollegeIndexRoute,
  AppEmployerIndexRoute: AppEmployerIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  CareerAdvisorRoute: CareerAdvisorRoute,
  CareerInsightsRoute: CareerInsightsRoute,
  CollegeAccessRoute: CollegeAccessRoute,
  EmployerAccessRoute: EmployerAccessRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  UpskillingRoute: UpskillingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
